apiVersion: "ryax.tech/v2.0"
kind: Processor
spec:
  id: flow-mapper
  human_name: Flow Mapper Component
  type: python3
  version: "3.0"
  logo: "logo.png"
  categories:
    - Processor
  dependencies:
    - pythonPackages.dbfread
    - pythonPackages.pandas
    - pythonPackages.numpy
    - pythonPackages.datar
  inputs:
  - help: DEM file
    human_name: Elevation map
    name: input_file
    type: file
  - help: hyperparameters json file
    human_name: hyperparameters json file
    name: input_json
    type: file
  outputs:
  - help: Directory with outputs
    human_name: Result directory
    name: python_outputs
    type: directory
